name: "Update Manifest and Commit Changes"
description: "Checks out the repository, sets up Node, installs dependencies, updates manifest.json, formats, and commits/pushes changes signing the commit."
inputs:
  manifestPath:
    description: "The path to the manifest.json file."
    required: false
    default: "${{ github.workspace }}/manifest.json"
  schemaPath:
    description: "The path to the plugin settings schema."
    required: false
    default: "${{ github.workspace }}/src/types/plugin-input.ts"
  pluginEntry:
    description: "The path to the plugin entry file."
    required: false
    default: "${{ github.workspace }}/src/index.ts"
  commitMessage:
    description: "The commit message."
    required: false
    default: "chore: updated manifest.json and dist build"
  nodeVersion:
    description: "The version of Node.js to use."
    default: "20.10.0"
  treatAsEsm:
    description: "If the package is set to be treated as ESM, it will replace __dirname occurrences."
    default: "false"
  sourcemap:
    description: "Generates the sourcemap for the compiled files"
    default: "false"
  minify:
    description: "Minifies the generated code"
    default: "true"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: |
        bun install --frozen-lockfile

    - name: Build project
      shell: bash
      run: |
        rm -rf dist
        echo "Compiling plugin..."
        bun build ${{ inputs.pluginEntry }} \
          ${{ inputs.minify == 'true' && '--minify' || ''}} \
          ${{ inputs.sourcemap == 'true' && '--sourcemap="linked"' || ''}} \
          --outdir dist --target node --entry-naming index.js
        echo "Compiling plugin types..."
        bun build ${{ inputs.schemaPath }} \
          ${{ inputs.minify == 'true' && '--minify' || ''}} \
          ${{ inputs.sourcemap == 'true' && '--sourcemap="linked"' || ''}} \
          --outdir plugin --target node --entry-naming index.js

    - name: Replace __dirname with import.meta.dirname
      if: ${{ inputs.treatAsEsm }}
      shell: bash
      run: |
        if [ "${{ inputs.treatAsEsm }}" = "true" ]; then
          sed -i 's/__dirname/import.meta.dirname/g' "${{ github.workspace }}/dist/index.js"
        fi

    - name: Update manifest configuration JSON
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs').promises;
          const path = require('path');

          async function updateManifest() {
            const manifestPath = '${{ inputs.manifestPath }}';
            const pluginPath = path.resolve('${{ github.workspace }}', 'plugin', 'index.js');

            let pluginSettingsSchema;
            try {
              // First, try to load as ESM
              try {
                const pluginModule = await import(`file://${pluginPath}`);
                pluginSettingsSchema = pluginModule.pluginSettingsSchema;

                if (!pluginSettingsSchema) {
                  throw new Error('pluginSettingsSchema not found in the ESM module');
                }
              } catch (esmError) {
                // If ESM import fails, try loading as CJS
                try {
                  const pluginModule = require(pluginPath);
                  pluginSettingsSchema = pluginModule.pluginSettingsSchema;

                  if (!pluginSettingsSchema) {
                    throw new Error('pluginSettingsSchema not found in the CJS module');
                  }
                } catch (cjsError) {
                  console.error('Error loading module as ESM and CJS:', esmError, cjsError);
                  process.exit(1);
                }
              }
            } catch (error) {
              console.error('Error loading module:', error);
              process.exit(1);
            }

            const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
            manifest["configuration"] = pluginSettingsSchema;

            function customReviver(key, value) {
              if (typeof value === "object" && value !== null) {
                if ("properties" in value && "required" in value) {
                  const requiredFields = new Set(value.required);
                  for (const [propKey, propValue] of Object.entries(value.properties)) {
                    if (typeof propValue === 'object' && 'default' in propValue) {
                      requiredFields.delete(propKey);
                    }
                  }
                  value.required = Array.from(requiredFields);
                  if (value.required.length === 0) {
                    delete value.required;
                  }
                }

                // Recursively apply to nested objects and arrays
                if (Array.isArray(value)) {
                  return value.map(item => JSON.parse(JSON.stringify(item), customReviver));
                } else {
                  return Object.fromEntries(
                    Object.entries(value).map(([k, v]) => [k, JSON.parse(JSON.stringify(v), customReviver)])
                  );
                }
              }
              return value;
            }

            const updatedManifest = JSON.stringify(manifest, customReviver, 2);
            await fs.writeFile(manifestPath, updatedManifest, 'utf8');
          }
          updateManifest();

    - name: Format manifest using Prettier
      shell: bash
      run: |
        bun add -DE prettier
        bun prettier --write .

    - name: Get GitHub App token
      if: env.APP_ID != '' && env.APP_PRIVATE_KEY != ''
      uses: tibdex/github-app-token@v1.7.0
      id: get_installation_token
      with:
        app_id: ${{ env.APP_ID }}
        private_key: ${{ env.APP_PRIVATE_KEY }}

    - name: Install dependencies for GitHub Auth
      shell: bash
      run: |
        bun add "@actions/github" glob

    - name: Update manifest.json and dist folder
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token || github.token }}
      run: |
        git add "${{ inputs.manifestPath }}"
        find ${{ github.workspace }}/dist \( -name "*.js" -o -name "*.map" \) -print0 | xargs -0 git add -f
        echo "Changed files:"
        echo "$(git diff-index --cached --name-only HEAD)"
        if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
          node -e "
            const fs = require('fs');
            const path = require('path');
            const github = require('@actions/github');
            const glob = require('glob');
            const manifestPath = path.relative('.', '${{ inputs.manifestPath }}');

            async function pushChanges() {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

              const context = github.context;
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const ref = 'heads/${{ github.ref_name }}';

              try {
                const currentCommit = await octokit.rest.git.getRef({
                  owner,
                  repo,
                  ref
                });

                console.log('Adding file:', manifestPath);
                const distPath = '${{ github.workspace }}/dist/';
                const distFiles = glob.sync(distPath + '**/*.{js,map}');
                const treeEntries = [
                  {
                    path: manifestPath,
                    mode: '100644',
                    type: 'blob',
                    content: fs.readFileSync(manifestPath, 'utf8'),
                  }
                ];
                for (const file of distFiles) {
                  const relativePath = path.relative('.', file);
                  console.log('Adding file:', relativePath);
                  treeEntries.push({
                    path: relativePath,
                    mode: '100644',
                    type: 'blob',
                    content: fs.readFileSync(file, 'utf8'),
                  });
                }
                const newTree = await octokit.rest.git.createTree({
                  owner,
                  repo,
                  base_tree: currentCommit.data.object.sha,
                  tree: treeEntries,
                });

                const newCommit = await octokit.rest.git.createCommit({
                  owner,
                  repo,
                  message: '${{ inputs.commitMessage }}',
                  tree: newTree.data.sha,
                  parents: [currentCommit.data.object.sha]
                });

                await octokit.rest.git.updateRef({
                  owner,
                  repo,
                  ref,
                  sha: newCommit.data.sha,
                  force: true
                });

                console.log('Changes pushed successfully');
              } catch (error) {
                console.error('Error pushing changes:', error);
                process.exit(1);
              }
            }

            pushChanges();
          "
        else
          echo "No changes to commit"
        fi
